version: "3"

volumes:
    postgres_data_dev: {}
    postgres_backup_dev: {}

services:
  rapidpro:
    image: ${DOCKER_IMAGE_NAME:-ilhasoft/rapidpro}:${DOCKER_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY:-SECRET_KEY}
      - EMAIL_HOST=${EMAIL_HOST:-localhost}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-admin@localhost.com}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-password}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - DATABASE_URL=${DATABASE_URL:-postgis://rapidpro:rapidpro@postgres:5432/rapidpro}
      - DATABASE_USE_SSL=${DATABASE_USE_SSL:-false} 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-123456}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-123456}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:-123456}
      - MAILROOM_URL=${MAILROOM_URL:-""}
      - MAILROOM_AUTH_TOKEN=${MAILROOM_AUTH_TOKEN:-""}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-""}
      - COMPRESS_ENABLED=${COMPRESS_ENABLED:-false}
      - COMPRESS_OFFLINE=${COMPRESS_OFFLINE:-false}
      - BRANDING_ENABLED=${BRANDING_ENABLED:-false}
      - BRANDING_FILES=${BRANDING_FILES:-https://github.com/push-platform/push-branding}
      - SETTINGS_FILE=${SETTINGS_FILE:-settings.py.dev}
    ports:
      - "8000:8000"
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: kartoza/postgis:9.6-2.4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-rapidpro}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-rapidpro}
      - POSTGRES_DB=${POSTGRES_DB:-rapidpro}
    restart: always
